In [8]:
import numpy as np 
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3,4))
np.random.random(size=(3,4))

array([[0.86059197, 0.8946352 , 0.94121097, 0.78002703],
       [0.43259545, 0.33479385, 0.26773529, 0.24899689],
       [0.18399448, 0.43156599, 0.56123242, 0.0204418 ]])

In [ ]:
from numpy.random import normal

normal_value = normal(size=(3,4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [9]:
#ndarry,陣列運算
normal_value * 10

array([[-16.60463509,   5.35784613,  13.18946601,  -7.68652435],
       [ 10.53574469,  -5.25543582,  -4.89532523,   0.83941722],
       [ 15.24655963,  10.62043218, -11.10615905,   8.45034145]])

In [10]:
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([-0.57438473,  0.12244009,  2.32111742])